import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { ServerThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Next app",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["cyrillic"] });
export default function RootLayout({ children }) {
  return (
    <ServerThemeProvider attribute="class">
      <html lang="en" suppressHydrationWarning>
        <body className="">
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
